name: "Continuous Integration"

on:
    workflow_dispatch:
    push:
        branches:
            - "master"
    pull_request:

jobs:
    tests:
        name: "Tests"
        runs-on: ubuntu-latest
        strategy:
          matrix:
            python-version: ["3.10", "pypy-3.10"]

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install Poetry
              run: pipx install poetry
            - name: Activate Python
              run: poetry env use "$Python3_ROOT_DIR/bin/python"
            - name: Python Version
              run: poetry run which python && poetry run python --version
            - name: Install Dependencies
              run: poetry install --with=dev
            - run: poetry run black --check .
            - run: poetry run isort --check .
            - run: poetry run mypy
            - run: poetry run pytest
            - run: poetry build
